name: CI
on:
  workflow_dispatch:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  unix:
    
    runs-on: ${{ matrix.os }}
     
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-10.15]
        include:
          - os: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1

      - name: Build Xtensor.jl
        shell: bash -l {0}
        run: |
          julia -E "using Pkg; Pkg.add(PackageSpec(name=\"CxxWrap\", version=\"0.11.2\"))"
          julia --project=. -E "using Pkg; Pkg.build()"

      - name: Test Xtensor.jl
        shell: bash -l {0}
        run: |
          julia --project=. -E "using Pkg; Pkg.test()"
